# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iduser',
            name='onJourneyTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wayfinder.Favourites'),
        ),
    ]
