# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0002_auto_20161018_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={'verbose_name_plural': 'Favourites'},
        ),
        migrations.AlterModelOptions(
            name='iduser',
            options={'verbose_name_plural': 'IDuser'},
        ),
        migrations.AlterField(
            model_name='iduser',
            name='carer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iduser',
            name='onJourneyTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wayfinder.Favourites'),
        ),
    ]
