# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0005_auto_20161107_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='iduser',
            name='timeStarted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
