# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0006_iduser_timestarted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iduser',
            name='timeStarted',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
