# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0008_auto_20161107_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='iduser',
            name='coords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
