# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0009_iduser_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iduser',
            name='timeStarted',
        ),
    ]
