# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0011_iduser_timestarted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iduser',
            name='timeStarted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
