# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0012_auto_20161110_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iduser',
            name='timeStarted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
